name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: node:13.5.0-alpine3.10
    steps:
    - name: Run a script
      run: |
        script.sh
    - name: Log node version
      run: |
        node -v
        cat /etc/os-release

